default:
    @just --list --unsorted

dir-name := `basename $(pwd)`

alias u := update
alias ad := add-deps
alias ck := create-kernel
alias ak := add-kernel
alias r := render
alias p := preview

update:
    poetry update

add-deps:
    poetry add --group dev jupyter
    poetry add numpy pandas matplotlib seaborn

create-kernel:
    python -m ipykernel install --user --name {{dir-name}}

add-kernel:
    echo -e "\njupyter: {{dir-name}}" >> notes/_quarto.yml

cd-src:
    cd "$(git rev-parse --show-toplevel || echo .)"
    cd src/

render: cd-src
    quarto render

preview: cd-src
    quarto preview
